name: SquishyCore
version: '${project.version}'
main: me.jay.squishycore.SquishyCore
api-version: 1.19
authors: [ Jay ]
description: Core for SquishyCore Server
commands:
  sc:
    description: Staffchat
    aliases: [staffchat, scsc]
  morphtool:
    description: gives a morphtool
    aliases: [mt]
  pvp:
    description: toggle pvp
    aliases: [p]
  quests:
    description: Quests gui to show progress.
    aliases: [quest, q, squishycorequests]

